### ISSUE TITLE
Need GCC 13+ support in `goreleaser-cross` for modern C++ features (DuckDB v1.3.0+ compatibility)

### ISSUE THREAD

**Issue by pskrbasu** [goreleaser/goreleaser-cross#106]
### Current Issue
The current `goreleaser-cross` images (based on Debian 11 Bullseye) only provide GCC 10.2.1, which is insufficient for projects requiring modern C++ features. Specifically, this affects projects using **DuckDB v1.3.0+** and related Go bindings.

#### DuckDB Version Compatibility
- **DuckDB v1.2.x**: Works with GCC 10.2.1 (C++11/C++14 support)
- **DuckDB v1.3.0+**: Requires GCC 13+ for C++17/C++20 features

#### Why This Matters
DuckDB v1.3.0+ introduced significant improvements and new features that require modern C++ standards, which we want to use in our project [Tailpipe](https://github.com/turbot/tailpipe).

### Error
When building with goreleaser-cross (GCC 10.2.1), projects encounter C++ standard library symbol errors:

```bash
# runtime/cgo
undefined reference to `std::__throw_bad_array_new_length()'
undefined reference to `std::__exception_ptr::exception_ptr::_M_release()'
```
These symbols are part of C++17/C++20 features not available in the older `libstdc++` version.

### C++ Standard Library ABI Incompatibility
The issue stems from DuckDB's build system changes in v1.3.0+:

1. **Explicit C++ Standard Flags**: DuckDB now sets `-std=c++17` or `-std=c++20` during compilation
2. **New C++ Features**: Uses modern C++ constructs that require GCC 13+
3. **Symbol Dependencies**: Links against newer C++ standard library symbols

### Current goreleaser-cross Limitations
- **Base OS**: Debian 11 (Bullseye) - released 2021
- **GCC Version**: 10.2.1 - supports up to C++14
- **C++ Standard Library**: `libstdc++` version too old for C++17/C++20
- **Update Frequency**: Base image updates are infrequent

### Update Base OS to Debian 12+ (Recommended)
Update goreleaser-cross to use Debian 12 (Bookworm) or newer, which provides:
- **GCC 13+**: Native support for C++17/C++20
- **Modern libstdc++**: Compatible with newer C++ standards
- **Long-term Support**: Debian 12 is stable and supported until 2026

Related: https://github.com/goreleaser/goreleaser-cross/issues/67

**Comment by troian** [comment]
I gave it a try some time ago and there were some issues. Feel free to play around, make target should allow you to build images locally.
I'll give it a try on my side again, tho it might take some time.
